import { useEffect, useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import api from '../api/axios';
import { formatDate } from '../utils/formatDate';
import { FiDownload } from 'react-icons/fi';
import jsPDF from 'jspdf';
import QRCode from 'qrcode';

const MyTicketsPage = () => {
  const [tickets, setTickets] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchTickets = useCallback(async () => {
    try {
      const res = await api.get('/orders/mytickets');
      setTickets(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchTickets();
  }, [fetchTickets]);

  const cancelTicket = async (ticketId) => {
    if (!window.confirm('Are you sure you want to cancel this ticket?')) return;
    try {
      await api.put(`/tickets/cancel/${ticketId}`);
      toast.success('Ticket cancelled');
      fetchTickets(); // refresh list
    } catch (err) {
      toast.error(err.response?.data?.message || 'Cancel failed');
    }
  };

  const downloadTicketPDF = async (ticket) => {
    const doc = new jsPDF('landscape', 'mm', 'a5');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Background
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    // Dashed border (simulated)
    doc.setDrawColor(100, 100, 100);
    doc.setLineDash([3, 2], 0);
    doc.rect(4, 4, pageWidth - 8, pageHeight - 8);
    doc.setLineDash([]);

    // Event title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(30, 30, 30);
    doc.text(ticket.eventId?.title || 'Event', 20, 30);

    // Attendee / Tier / Status
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`Attendee: ${ticket.attendeeId?.name || 'You'}`, 20, 45);
    doc.text(`Ticket Tier: ${ticket.tierName}`, 20, 55);
    doc.text(`Status: ${ticket.status.toUpperCase()}`, 20, 65);

    // Event details
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    if (ticket.eventId?.startDate) {
      doc.text(`Date: ${formatDate(ticket.eventId.startDate)}`, 20, 80);
    }
    if (ticket.eventId?.venue) {
      doc.text(`Venue: ${ticket.eventId.venue}`, 20, 90);
    }

    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 100, pageWidth - 20, 100);

    // ----- Generate QR code -----
    // The QR code will contain a verification URL (or just the ticket ID)
    const verificationUrl = `${window.location.origin}/verify-ticket/${ticket._id}`;
    
    let qrDataUrl;
    try {
      qrDataUrl = await QRCode.toDataURL(verificationUrl, {
        width: 200,
        margin: 1,
        color: { dark: '#000000', light: '#ffffff' },
      });
    } catch (err) {
      console.warn('QR code generation failed', err);
      // Fallback placeholder
      doc.setFillColor(240, 240, 240);
      doc.rect(20, 110, pageWidth - 40, 25, 'F');
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text('QR CODE (verification link)', pageWidth / 2, 125, { align: 'center' });
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text(`Ticket ID: ${ticket._id}`, 20, pageHeight - 15);
      doc.text('Generated by EventTix', pageWidth - 20, pageHeight - 15, { align: 'right' });
      doc.save(`ticket-${ticket._id.slice(-6)}.pdf`);
      return;
    }

    // Add QR code image to PDF (centered, with a nice size)
    const qrSize = 30; // mm
    const qrX = pageWidth / 2 - qrSize / 2;
    const qrY = 110;
    doc.addImage(qrDataUrl, 'PNG', qrX, qrY, qrSize, qrSize);

    // Label under QR code
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text('Scan to verify ticket', pageWidth / 2, qrY + qrSize + 5, { align: 'center' });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Ticket ID: ${ticket._id}`, 20, pageHeight - 15);
    doc.text('Generated by EventTix', pageWidth - 20, pageHeight - 15, { align: 'right' });

    // Save the PDF
    doc.save(`ticket-${ticket._id.slice(-6)}.pdf`);
  };

  if (loading)
    return (
      <div className="text-center py-8">
        <div className="animate-pulse space-y-4">
          <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-1/3 mx-auto" />
          <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2 mx-auto" />
        </div>
      </div>
    );

  return (
    <div>
      <h1 className="text-3xl font-bold gradient-text mb-8">My Tickets</h1>

      {tickets.length === 0 ? (
        <div className="text-center py-16 glass rounded-2xl">
          <p className="text-xl text-gray-500 dark:text-gray-400">No tickets purchased yet.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {tickets.map((ticket) => (
            <motion.div
              key={ticket._id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
              className="glass rounded-xl p-5 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4"
            >
              <div className="flex-1">
                <h3 className="font-semibold text-xl dark:text-white">
                  {ticket.eventId?.title || 'Event'}
                </h3>
                <p className="text-gray-600 dark:text-gray-300">
                  {ticket.tierName}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  Issued: {formatDate(ticket.issuedAt)} &nbsp;|&nbsp;
                  Status:{' '}
                  <span
                    className={
                      ticket.status === 'valid'
                        ? 'text-green-500 font-medium'
                        : 'text-red-500 font-medium'
                    }
                  >
                    {ticket.status}
                  </span>
                </p>
              </div>

              <div className="flex items-center gap-3">
                <button
                  onClick={() => downloadTicketPDF(ticket)}
                  className="flex items-center gap-1 px-4 py-2 bg-primary-600 text-white rounded-full hover:bg-primary-700 transition text-sm"
                >
                  <FiDownload className="w-4 h-4" />
                  PDF
                </button>

                {ticket.status === 'valid' && (
                  <button
                    onClick={() => cancelTicket(ticket._id)}
                    className="px-4 py-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition text-sm"
                  >
                    Cancel
                  </button>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
};

export default MyTicketsPage;